### ISSUE TITLE
Permanent URLs

### ISSUE THREAD

**Issue by Rafiot** [CIRCL/lookyloo#12]
Have a permanent URL for each run

**Comment by rysiekpl** [comment]
+1, that would be very useful. A simple way to do this would be to reverse the numbering (first scraped URL would always end up as `/tree/0`, second as `/tree/1`, and so on).

**Comment by Rafiot** [comment]
I already have a partial support for uuid for each run, I'll use it asap (so when we delete a run, the links stay the same)

**Comment by Rafiot** [comment]
Fixed: https://github.com/CIRCL/lookyloo/commit/e14a0150a00bb73711cbb2ec4311620c42c0d49f
