### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by rysiekpl** [CIRCL/lookyloo#17]
It would be an amazing improvement if screenshots of each of the HTML pages retrieved in the process of scraping were available via the interface for inspection (this would be very informative when researching a targeting phishing attack, for instance).

**Comment by Rafiot** [comment]
Absolutely, I need to add a link to the screenshot: it is already taken by the library and stored, just not used.

**Comment by Rafiot** [comment]
Fixed for a very long time.
