### ISSUE TITLE
Option to disable or rename session cookies

### ISSUE THREAD

**Issue by rysiekpl** [CIRCL/lookyloo#18]
LookyLoo sets a session cookie (boringly named `session`). This is an issue if LookyLoo is being used behind a reverse proxy with an access authorization system that also happens to set a cookie named `session` -- the effect is that:

1. request comes to the reverse proxy; reverse proxy does its magic and sets its `session` cookie to persist the authorization status;
1. request is sent further to the upstream (i.e. LookyLoo).
1. LookyLoo sets its own `session` cookie, since the one set by the reverse proxy does not conform to whatever LookyLoo expects
1. response is returned to the client -- with the LookyLoo `session` cookie overwriting the reverse proxy cookie
1. upon the next request, the whole dance starts over

This results in no session persistence and LookyLoo not working properly behind such a reverse proxy. It would be swell if it were possible to change the *name* of the session cookie set by LookyLoo so as not to clash with potential reverse proxy.

The cookie seems not necessary -- blocking `Set-Cookie` on the reverse proxy (so that it does not reach the browser) does not seem to result in loss of functionality.

----

For the record, a quick and dirty workaround for `nginx` is:

1. make sure the reverse proxy session cookie is not sent back to LookyLoo upstream;
2. make sure that any `Set-Cookie` header set by LookyLoo is blocked from reaching the user browser.

There does not seem to be a way of modifying cookie headers sent to upstreams directly in `nginx` config), so point 1. would either have to use Lua (like in our case) or some other method; point 2. can be done with `proxy_hide_header Set-Cookie;` `nginx` config directive.

**Comment by Rafiot** [comment]
Gotcha, thank you for the report, I fixed it :) 

```$ (git::master) curl -s -D- http://localhost:5000/ | head -n 20    
HTTP/1.0 200 OK                  
Content-Type: text/html; charset=utf-8                             
Content-Length: 5798             
Set-Cookie: lookyloo=eyJfcGVybWFuZW50Ijp0cnVlfQ.DZVqIg.-en8CwHXyYHrzozdDoAwJG49AP8; Expires=Sun, 22-Apr-2018 16:24:02 GMT; HttpOnly; Path=/                             
Server: Werkzeug/0.14.1 Python/3.6.3                               
Date: Thu, 22 Mar 2018 16:24:02 GMT                                
```

**Comment by rysiekpl** [comment]
Woo! Thanks!
