### ISSUE TITLE
Latest changes introduced Python 3.6 dependency and broke Dockerfile

### ISSUE THREAD

**Issue by sw-mschaefer** [CIRCL/lookyloo#21]
In commit f6345e47e18c5db9d2498139435454c108f85607 [Formatted string literals](https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings) are used (see this [line]( https://github.com/CIRCL/lookyloo/commit/f6345e47e18c5db9d2498139435454c108f85607#diff-28ec5eee3d9389f9f5081e438832920dR65)).

This introduces a dependency to a minimum Python version of 3.6, which is not available on many distributions. It also breaks the current Dockerfile, since it is based on Debian Stretch, which has Python 3.4

**Comment by Rafiot** [comment]
Woops, right. 

I'll switch the docker image to ubuntu 18.04.

**Comment by Rafiot** [comment]
Should be fixed by : https://github.com/CIRCL/lookyloo/commit/a4bdbbebd40cdb6a5b68d1fdd3f5f2ad70df3922

Thank you for the notification.
