### ISSUE TITLE
Anonymous submit.

### ISSUE THREAD

**Issue by Th4nat0s** [CIRCL/lookyloo#25]
It will be nice to have a "don't remember me " button which allow the scanned website to not be published. ( PORN^WGDPR need )

**Comment by Rafiot** [comment]
I'll go for "not indexed". If you want real private, you should run it in house... :p

**Comment by Th4nat0s** [comment]
I trust CIRCL, and a thing less to maintain is a good thing to me :). 

Anyway, I had read the code, I think I could handle this one, got free time this weekend. 

Since no DB is involved, Why not creating a file "noindex.txt" file in folder of the guid at creation (in scrape).  And an additional marker in the redis (in the cache dict)  set in _set_report and  _set_report_cache when building the cache. 

Then It need only an additional method ( IE report_cache_public ) in the loop of the route "/" which build the list omiting the hidden one. 

By doing this, It address only the front listing, not the whole product, if you got the link with the UID you may use it and share it.

**Comment by Rafiot** [comment]
I was considering an even lazier approach: put a `no_index` file in the directory of the scrapped content and skipping that in the listing (the same way it is done in case the HAR file is broken/missing/fucked up).
