### ISSUE TITLE
Collapse/expand tree/pop up window ambiguity 

### ISSUE THREAD

**Issue by quinnnorton** [CIRCL/lookyloo#29]
expand/collapse tree current links to windows, but text controls pop up window. Put text and tree circle on the same horizontal rule, and give them both a similar border, drop the inheritance like from between them. (or possibly from the right hand side of the new border?)

**Comment by Rafiot** [comment]
Related: https://github.com/CIRCL/lookyloo/issues/40 (needs a rewrite)

**Comment by Rafiot** [comment]
Fixed with new hostnode popup.
