### ISSUE TITLE
Inheritance point on pop up windows is the same circle as the tree

### ISSUE THREAD

**Issue by quinnnorton** [CIRCL/lookyloo#34]
this is visually awkward, but also implies functionality where there is none. 

Make inheritance a small dot, to make it visually unobtrusive and to make it clear it has no functionality.

**Comment by Rafiot** [comment]
Related: https://github.com/CIRCL/lookyloo/issues/40 (needs a rewrite)

**Comment by Rafiot** [comment]
Hostnode popup.
