### ISSUE TITLE
Add basic user agent support

### ISSUE THREAD

**Issue by quinnnorton** [CIRCL/lookyloo#36]
A few user agents, and  free text box for folks who want to shoot themselves in the foot. (with a link to info on user agents so they can avoid their feet if they like)

**Comment by Rafiot** [comment]
Partial implementation: https://github.com/CIRCL/lookyloo/commit/346f2d6ec31e6b16a6593f038039e7a7c3a97da4

TODO: 
* [ ] reorganize the scraping page
* [ ] pass the OS name and the browser name

**Comment by Rafiot** [comment]
Meta issue for missing functionalities: https://github.com/CIRCL/lookyloo/issues/47
