### ISSUE TITLE
Nginx Gateway Timeout

### ISSUE THREAD

**Issue by ahezza** [CIRCL/lookyloo#38]
Hello,

I am running Lookyloo in Production, and have nginx running.

Whenever I submit a URL for scanning, I get a page returned saying:

```
504 Gateway Time-out
nginx/1.14.0 (Ubuntu)

```
Here is the settings under vim /etc/nginx/sites-enabled/lookyloo 

```
server {
    listen 80;
    server_name lookyloo;

    location / {
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 10;
        proxy_read_timeout 10;
        proxy_pass http://localhost:5100/;
    }
}
```

I can't find a solution to this issue, are you able to assist?

**Comment by ahezza** [comment]
I have checked the nginx logs, and here's the error I'm getting

`2019/04/08 13:00:32 [error] 6529#6529: *1578 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: lookyloo, request: "POST /scrape HTTP/1.1", upstream: "http://127.0.0.1:5100/scrape", host: "127.0.0.1", referrer: "http://127.0.0.1/scrape"`

**Comment by ahezza** [comment]
Fixed it myself, changing the increasing the proxy timeout setting under /etc/nginx/sites-enabled/lookyloo fixed it:

`        proxy_read_timeout 600;`

**Comment by Rafiot** [comment]
oh yeah, I increased it to 300 recently, but 600 or more may be required. It's a problem, but I'm not sure how to solve it.

**Comment by joyfulmagician** [comment]
I can't solve this error too...

**Comment by joyfulmagician** [comment]
I set them as follows:
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;
fastcgi_read_timeout 300;

**Comment by Rafiot** [comment]
Look in the logs, that's going to be a different issue, the really long timeout shouldn't be needed anymore.

**Comment by joyfulmagician** [comment]
> Look in the logs, that's going to be a different issue, the really long timeout shouldn't be needed anymore.

2024/10/21 13:43:11 [error] 8343#8343: *316 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 66.118.255.35, server: cadideals.com, request: "POST /admin/products/upload-csv HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock", host: "cadideals.com", referrer: "https://cadideals.com/admin/products/"

**Comment by Rafiot** [comment]
That's a php related issue, it has nothing to do with lookyloo, afaict.
