### ISSUE TITLE
Cannot scroll right or down in workspace

### ISSUE THREAD

**Issue by quinnnorton** [CIRCL/lookyloo#49]
scroll is constrained to tree, but workspace often exceeds tree, without being able to access data or controls

![Screen Shot 2019-05-27 at 2 30 52 PM](https://user-images.githubusercontent.com/4722614/58419958-413ffc80-808c-11e9-8b96-6c236762d6de.png)

**Comment by Rafiot** [comment]
Hostnode popup.
