### ISSUE TITLE
Clicking on a node circle backgrounds any open window

### ISSUE THREAD

**Issue by quinnnorton** [CIRCL/lookyloo#50]
after you open a node window, if you click on a node circle to expand or collapse a part of the tree, it backgrounds the window (and all other windows) until you close and open them again. 

![Screen Shot 2019-05-27 at 2 39 26 PM](https://user-images.githubusercontent.com/4722614/58420479-aea05d00-808d-11e9-925e-73ec2ae52649.png)

**Comment by Rafiot** [comment]
Hostnode popup.
