### ISSUE TITLE
Report lookup redirects to index despite tree_uuid created

### ISSUE THREAD

**Issue by delpes** [CIRCL/lookyloo#52]
I observed the following behavior using [https://www.circl.lu/urlabuse/](https://www.circl.lu/urlabuse/)

1. Go to https://www.circl.lu/urlabuse/
2. Insert a Link and hit _Run lookup_
3. Click the Link 'See on Lookyloo'
4. You are redirected to the index

The link contains a valid `tree_uuid` but it seems that `lookup_report_dir` doesn't return a valid `report_dir` and thus redirects you to the index.

After some moments the report is viewable.

Expected behavior:
Show an _in progress_ notice while keeping the url intact to enable manuel refresh (F5) or redirect to the finished report once it is done.

**Comment by Rafiot** [comment]
Yeah, I need to make it more reliable, lookyloo is a lot slower than urlabuse and you need to wait ~30-60s before the tree is visible.

**Comment by Rafiot** [comment]
It now displays an error message telling you to try again later. There is currently no way to keep track of a capture happening in the background, so it will do for now.
