### ISSUE TITLE
show redirects vertically rather than horizontally?

### ISSUE THREAD

**Issue by femto113** [CIRCL/lookyloo#56]
Because they don't return resources to the browser I think redirects are qualitatively different from other reference types like script and css sources and iframes, but they currently manifest in the same way as depth in the tree.   Since redirects typically happen before resources are loaded there would generally be lots of extra vertical space available in the earlier parts of the tree, so perhaps they could be oriented vertically to emphasize this difference?  For example cnn.com (https://lookyloo.circl.lu/tree/5ea5cebb-9223-42db-bdeb-34543b237b05)  shows 

```
cnn.com --> www.cnn.com --> www.cnn.com --> edition.cnn.com --> ... resources ...
```

would it be possible to get them to render more like this

```
cnn.com
   V
www.cnn.com
   V
www.cnn.com
   V
edition.cnn.com --> ... resources ...
```

**Comment by Rafiot** [comment]
PRs are welcome, but that sounds like a nightmare to implement, closing for now.
