### ISSUE TITLE
Consider having basic interaction with the page

### ISSUE THREAD

**Issue by Phyks** [CIRCL/lookyloo#63]
Hi,

I gave a try at lookyloo on lemonde.fr and it appears it is only doing an initial loading the page and checking the resources. Indeed, many external scripts do not appear in https://lookyloo.circl.lu/tree/d530bbaf-f20c-42eb-b16e-9d4537fc206e.

When browsing the site with a regular browser, it seems a large number of scripts is loaded upon scrolling down. What about considering basic interaction with the page in Lookyloo (scrolling to the bottom for instance, this could however have unintended side effects with infinite scrolling pages)?

Best,

**Comment by Rafiot** [comment]
Hi,

Thank you for your feedback. It is planned to have some interactions with the website. For now, the development version is supposed to scroll down on the the page (https://github.com/viper-framework/ScrapySplashWrapper/blob/master/scrapysplashwrapper/crawler.py#L47), and I hoped it would be enough for lemonde, but it's not (or that script simply doesn't work). I need to play a bit more with it.
The other thing that should (?) help is passing cookies (typically in that case, the GDPR cookie). but I need to try with lemonde specifically (it already allows to scrape a google mailbox).

**Comment by Rafiot** [comment]
Scrolling down on the page should now works as expected, please open a new issue if needed.
