### ISSUE TITLE
Explanation about redirection ?

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/lookyloo#64]
Hello,

With the new version (updated today on my server), I got some troubles with redirection.
For example, if I try to analyze this url:
hxxp://russia.p4nd4.land/1.html
I don't see the redirection to the other pages: from 1.html to 5.html
It seems that there is some troubles with t.co redirection too.

Do you have any information for the redirection ?

Best regards,

**Comment by Rafiot** [comment]
We get the initial redirects from this entry in the [HAR export](http://www.softwareishard.com/blog/har-12-spec/):
`redirectURL [string] - Redirection target URL from the Location response header.` 

So in your case, it's an HTTP redirect, so it doesn't set that header.

I did it the [easy way](https://github.com/viper-framework/har2tree/blob/master/har2tree/parser.py#L509) but it will require some more tweaks, and probably mark the HTML redirects differently.

**Comment by FafnerKeyZee** [comment]
For t.co, from the header (via curl)
curl https://t.co/REMOVED?amp=1 -I

HTTP/2 301 
cache-control: private,max-age=300
date: Thu, 13 Feb 2020 10:04:15 GMT
expires: Thu, 13 Feb 2020 10:09:15 GMT
location: https://*REMOVED*
server: tsa_f
set-cookie: muc=68b15902-7ff7-4765-84d8-d783ade72374; Max-Age=63072000; Expires=Sat, 12 Feb 2022 10:04:15 GMT; Domain=t.co
strict-transport-security: max-age=0
vary: Origin
x-connection-hash: 504674ad9a6cee999a3d2f4e2ed9c40d
x-response-time: 115

But thanks for the information :)

**Comment by Rafiot** [comment]
Hmmmm so for some reason, the location header isn't in the har file... (so we don't have the redirectURL one either).

**Comment by FafnerKeyZee** [comment]
Hummm,
When I run it in splash:

`<html><head><noscript>&lt;META http-equiv="refresh" content="0;URL=https://*removed*"&gt;</noscript><title>*removed*</title><script>window.opener = null; location.replace("*removed*")</script></head></html>`

**Comment by Rafiot** [comment]
Oh. if you run that request with curl or wget, you get a HTTP 301 response. If you come with a browser, you get a HTML page:
```html
<head><noscript>
<META http-equiv="refresh" content="0;URL=https://pastebin.com/Yh9nJ7gs">
</noscript>
<title>https://pastebin.com/Yh9nJ7gs</title></head>
<script>window.opener = null; location.replace("https:\/\/pastebin.com\/Yh9nJ7gs")</script>
```

**Comment by Rafiot** [comment]
right, that  :D

**Comment by FafnerKeyZee** [comment]
So let's create an issue for this ? or better to close for the moment ?

**Comment by Rafiot** [comment]
Yeah, let's create an other issue "Display HTML redirects on the index page", it will be better. If you have time for that now, go for it, otherwise I'll do it.
