### ISSUE TITLE
404 code on website leads to internal error

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/lookyloo#66]
Hey,

With the latest version, if I submit a website with a 404 code return, lookyloo is crashing with an internal error 500.
logs are there: https://pastebin.com/Yh9nJ7gs
But when calling it directly from command line:
```
curl 'http://localhost:8050/render.html?url=http://domain/page.html&timeout=10&wait=0.5'
<!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /404.html was not found on this server.</p>

</body></html>
```
har, png and html keys should exist...

best regards,

**Comment by Rafiot** [comment]
That should be properly handled now.
